---
name: "tagged-release"

on: [workflow_dispatch]
 # push:
 #   tags:
 #     - "v*"
  
  
  

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "macos-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prep workspace
        run: |
             brew install automake
             gem install ronn
      
      - name: "Auto Conf"
        run: autoreconf --install --warnings=all
      
      - name: "Configure"
        run: ./configure
       
      - name: "Make"
        run: make
        
     - name: Codesign executable
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
          security create-keychain -p <your-password> build.keychain security default-keychain -s build.keychain
          security unlock-keychain -p <your-password> build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k <your-password> build.keychain
          /usr/bin/codesign --force -s <identity-id> ./flock -v
        
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            LICENSE.md
            flock

