---
name: "tagged-release"

on: [workflow_dispatch]
 # push:
 #   tags:
 #     - "v*"
  
  
  

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "macos-latest"

    steps:
      # ...
      
      - name: "Lost"
        run: pwd
        
      - name: "Contents"
        run: ls -lah ./..      
      
      - name: "Configure"
        run: ./configure
       
      - name: "Make"
        run: make
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            LICENSE.txt
            *

